### ISSUE TITLE
Pocket Network integration

### ISSUE THREAD

**Issue by luyzdeleon** [TezosRio/TezosJ_SDK#1]
### Overview: 
Currently TezosJ_SDK supports connecting to the network via a centralized provider. In this issue the Pocket Network team would like to propose an integration between Pocket Core MVP and TezosJ_SDK, allowing developers to utilize the Pocket Core MVP network of nodes (currently 6 different infrastructure providers) to connect to the Tezos blockchain using a trusted decentralized network of nodes via random access across different requests.

### Scope of the integration:

- Modification of the [Tezos Gateway](https://github.com/TezosRio/TezosJ_SDK/blob/master/tezosj_android/src/main/java/milfont/com/tezosj_android/data/TezosGateway.java) to support both centralized providers and Pocket Network.
- Update interfaces using the `TezosGateway` class.
- Expose configuration options for Pocket Network usage.

### References:
Website: [pokt.network](https://pokt.network)
Developer Portal: [docs.pokt.network](https://docs.pokt.network)
Pocket Core MVP: [Click here](https://www.pokt.network/pocket-core-mvp/)

**Comment by TezosRio** [comment]
We are thrilled with your intention to participate in TezosJ_SDK development. Thank you for your support and trust.
